name: Connect OIDC

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      repository:
        description: Name of the repository
        required: true
        type: string
      subscription:
        description: Azure subscription id (guid)
        required: true
        type: string
      resourceGroup:
        description: Name of the resource group
        required: true
        type: string

run-name: "Repository: '${{ inputs.repository }}' Resource Group: '${{ inputs.resourceGroup }}'"

env:
  DESCRIPTION: Creates a service principal and uses it to configure a repository to enable deployments to azure
  OIDC_REPOSITORY_URL: ${{ github.server_url }}/${{ github.repository_owner }}/${{ inputs.repository }}
  AZURE_RESOURCE_GROUP_URL: https://portal.azure.com/#@${{ vars.AZURE_TENANT_ID }}/resource/subscriptions/${{ inputs.subscription }}/resourceGroups/${{ inputs.resourceGroup }}/overview

jobs:
  print:
    name: OIDC Connection Request
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "### @${{ github.triggering_actor }} would like to connect repository [${{inputs.repository}}](${{ env.OIDC_REPOSITORY_URL }}) to Azure resource group [${{ inputs.resourceGroup }}](${{ env.AZURE_RESOURCE_GROUP_URL }})" >> $GITHUB_STEP_SUMMARY
          echo "Triggered by: @${{ github.triggering_actor }}" >> $GITHUB_STEP_SUMMARY

  connect:
    name: OIDC Connection
    runs-on: ubuntu-latest
    environment: default

    steps:
      - uses: actions/checkout@v4

      - name: Az CLI login
        uses: azure/login@v1
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          allow-no-subscriptions: true

      - name: Validate Resource Group
        run: |
          set +e
          rg_output=$( az group show --subscription "${{ inputs.subscription }}" --name "${{ inputs.resourceGroup }}" 2>&1 )
          rg_output_status=$?

          if [ $rg_output_status -ne 0 ]; then
              while IFS= read -r line ; do echo "::error::$line"; done <<< "$rg_output"
              exit $rg_output_status
          fi

      - name: Validate Repository
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_GITHUB_TOKEN }}
        run: |
          set +e
          repo_output=$( gh repo view "${{ github.repository_owner }}/${{ inputs.repository }}" --json id,url 2>&1 )
          repo_output_status=$?

          if [ $repo_output_status -ne 0 ]; then
              while IFS= read -r line ; do echo "::error::$line"; done <<< "$repo_output"
              exit $repo_output_status
          fi

          set -e
          repo_secrets=$( gh secret list -R "${{ github.repository_owner }}/${{ inputs.repository }}" )
          repo_variables=$( gh variable list -R "${{ github.repository_owner }}/${{ inputs.repository }}" )

          for VARIABLE in "AZURE_TENANT_ID" "AZURE_CLIENT_ID"
          do
              if [[ $repo_variables == *"$VARIABLE"* ]]; then
                  echo "::error::Repository already contains variable '$VARIABLE'."; exit 1
              fi

              if [[ $repo_secrets == *"$VARIABLE"* ]]; then
                  echo "::error::Repository already contains secret '$VARIABLE'."; exit 1
              fi
          done

      - name: Write Summary
        run: |
          echo "#### Successfully connected repository [${{inputs.repository}}](${{ env.OIDC_REPOSITORY_URL }}) to Azure resource group [${{ inputs.resourceGroup }}](${{ env.AZURE_RESOURCE_GROUP_URL }})" >> $GITHUB_STEP_SUMMARY
          echo "To use..." >> $GITHUB_STEP_SUMMARY

      - name: Done
        run: |
          echo done.
