name: Connect OIDC

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      repository:
        description: Name of the repository
        required: true
        type: string
      subscription:
        description: Azure subscription id (guid)
        required: true
        type: string
      resourceGroup:
        description: Name of the resource group
        required: true
        type: string

env:
  DESCRIPTION: Creates a service principal and uses it to configure a repository to enable deployments to azure
  OIDC_REPOSITORY_URL: ${{ github.server_url }}/${{ github.repository_owner }}/${{ inputs.repository }}
  AZURE_RESOURCE_GROUP_URL: https://portal.azure.com/#@${{ vars.AZURE_TENANT_ID }}/resource/subscriptions/${{ inputs.subscription }}/resourceGroups/${{ inputs.resourceGroup }}/overview

jobs:
  print:
    name: Request Details
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "### Connecting repository [${{inputs.repository}}](${{ env.OIDC_REPOSITORY_URL }}) to Azure resource group [${{ inputs.resourceGroup }}](${{ env.AZURE_RESOURCE_GROUP_URL }})" >> $GITHUB_STEP_SUMMARY
          echo "Triggered by: ${{ github.triggering_actor }}" >> $GITHUB_STEP_SUMMARY

  connect:
    name: Connect OIDC
    runs-on: ubuntu-latest
    environment: default

    steps:
      - uses: actions/checkout@v4

      - name: Az CLI login
        uses: azure/login@v1
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          allow-no-subscriptions: true

      - name: Validate Resource Group
        run: |
          az group show --subscription ${{ inputs.subscription }} -n ${{ inputs.resourceGroup }}

      - name: Validate Repository
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_GITHUB_TOKEN }}
        run: |
          gh repo view ${{ github.repository_owner }}/${{ inputs.repository }} --json id,url

      - name: Done
        run: |
          echo done.
